using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using LighthouseExtends.Popup.Editor.ScriptableObject;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEngine;

namespace LighthouseExtends.Popup.Editor.ScriptGenerator
{
    public static class PopupEntityFactoryGenerator
    {
        const string SettingsDefaultAssetPath = "Assets/Settings/PopupGenerateSettings.asset";

        [DidReloadScripts]
        static void OnScriptsReloaded()
        {
            Generate();
        }

        [MenuItem("Lighthouse Extends/Auto Generate/Generate Popup Entity Factory")]
        static void GenerateFromMenu()
        {
            Generate();
        }

        [MenuItem("Lighthouse Extends/Settings/PopupGenerateSettings")]
        static void ShowSettings()
        {
            var settings = LoadOrCreateSettings();
            if (settings != null)
            {
                Selection.activeObject = settings;
            }
        }

        static void Generate()
        {
            var settings = LoadSettings();
            if (settings == null || string.IsNullOrEmpty(settings.PopupEntityFactoryFilePath))
            {
                return;
            }

            var popupDataInterface = typeof(IPopupData);
            var popupSetupOpenType = typeof(IPopupSetup<,>);

            var allTypes = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(SafeGetTypes)
                .ToArray();

            var dataTypes = allTypes
                .Where(t => t.IsClass && !t.IsAbstract && popupDataInterface.IsAssignableFrom(t))
                .ToArray();

            if (dataTypes.Length == 0)
            {
                return;
            }

            var mappings = new List<(Type Data, Type Popup, Type Presenter)>();

            foreach (var dataType in dataTypes)
            {
                var popupType = allTypes.FirstOrDefault(t =>
                    t.IsClass && !t.IsAbstract &&
                    t.GetInterfaces().Any(i =>
                        i.IsGenericType &&
                        i.GetGenericTypeDefinition() == popupSetupOpenType &&
                        i.GetGenericArguments()[1] == dataType));

                if (popupType == null)
                {
                    Debug.LogWarning($"[PopupEntityFactoryGenerator] No IPopupSetup implementation found for {dataType.Name}. Skipped.");
                    continue;
                }

                var setupInterface = popupType.GetInterfaces().First(i =>
                    i.IsGenericType &&
                    i.GetGenericTypeDefinition() == popupSetupOpenType &&
                    i.GetGenericArguments()[1] == dataType);

                var presenterType = setupInterface.GetGenericArguments()[0];
                mappings.Add((dataType, popupType, presenterType));
            }

            if (mappings.Count == 0)
            {
                return;
            }

            var content = BuildContent(settings.PopupEntityFactoryClassName, settings.PopupEntityFactoryNamespace, mappings);
            WriteContent(content, settings.PopupEntityFactoryFilePath);
        }

        static string BuildContent(string className, string namespaceName, List<(Type Data, Type Popup, Type Presenter)> mappings)
        {
            var extraNamespaces = mappings
                .SelectMany(m => new[] { m.Data.Namespace, m.Popup.Namespace, m.Presenter.Namespace })
                .Where(ns => !string.IsNullOrEmpty(ns) && ns != namespaceName)
                .Distinct()
                .OrderBy(ns => ns)
                .ToArray();

            var sb = new StringBuilder(4 * 1024);

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated by PopupEntityFactoryGenerator.");
            sb.AppendLine("// DO NOT EDIT MANUALLY.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine("using LighthouseExtends.Popup;");
            sb.AppendLine("using VContainer;");
            foreach (var ns in extraNamespaces)
            {
                sb.AppendLine($"using {ns};");
            }
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public sealed class {className} : IPopupEntityFactory");
            sb.AppendLine("    {");
            sb.AppendLine("        readonly IObjectResolver objectResolver;");
            sb.AppendLine("        readonly IPopupInstanceFactory popupInstanceFactory;");
            sb.AppendLine();
            sb.AppendLine($"        public {className}(IObjectResolver objectResolver, IPopupInstanceFactory popupInstanceFactory)");
            sb.AppendLine("        {");
            sb.AppendLine("            this.objectResolver = objectResolver;");
            sb.AppendLine("            this.popupInstanceFactory = popupInstanceFactory;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public UniTask<PopupEntity> CreateAsync(IPopupData data, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            return data switch");
            sb.AppendLine("            {");
            foreach (var (dataType, popupType, presenterType) in mappings)
            {
                sb.AppendLine($"                {dataType.Name} d => CreatePopupEntityAsync<{popupType.Name}, {presenterType.Name}, {dataType.Name}>(\"{popupType.Name}\", d, ct),");
            }
            sb.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(data), data.GetType().FullName, \"Unknown popup data type\")");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        async UniTask<PopupEntity> CreatePopupEntityAsync<TPopup, TPopupPresenter, TPopupData>(");
            sb.AppendLine("            string popupAddress,");
            sb.AppendLine("            TPopupData data,");
            sb.AppendLine("            CancellationToken ct)");
            sb.AppendLine("            where TPopup : IPopup, IPopupSetup<TPopupPresenter, TPopupData>");
            sb.AppendLine("            where TPopupPresenter : IPopupPresenter, new()");
            sb.AppendLine("            where TPopupData : IPopupData");
            sb.AppendLine("        {");
            sb.AppendLine("            var popupInstance = await popupInstanceFactory.CreatePopupInstance<TPopup>(popupAddress, ct);");
            sb.AppendLine("            var popupPresenter = new TPopupPresenter();");
            sb.AppendLine("            objectResolver.Inject(popupPresenter);");
            sb.AppendLine("            popupInstance.Setup(popupPresenter, data);");
            sb.AppendLine("            return new PopupEntity(popupInstance, popupPresenter, data);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        static void WriteContent(string content, string filePath)
        {
            var directoryPath = Path.GetDirectoryName(filePath);
            if (!Directory.Exists(directoryPath))
            {
                Directory.CreateDirectory(directoryPath);
            }

            if (File.Exists(filePath))
            {
                var existing = File.ReadAllText(filePath, Encoding.UTF8);
                if (existing == content)
                {
                    return;
                }
            }

            File.WriteAllText(filePath, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

            var assetPath = "Assets" + filePath.Substring(Application.dataPath.Length).Replace('\\', '/');
            AssetDatabase.ImportAsset(assetPath, ImportAssetOptions.ForceUpdate);
            AssetDatabase.Refresh();
            Debug.Log("[PopupEntityFactoryGenerator] Generated.");
        }

        static IEnumerable<Type> SafeGetTypes(System.Reflection.Assembly assembly)
        {
            try
            {
                return assembly.GetTypes();
            }
            catch
            {
                return Array.Empty<Type>();
            }
        }

        static PopupGenerateSettings LoadOrCreateSettings()
        {
            var settings = LoadSettings();
            if (settings != null)
            {
                return settings;
            }

            var fsDirPath = Path.Combine(Application.dataPath, "Settings");
            if (!Directory.Exists(fsDirPath))
            {
                Directory.CreateDirectory(fsDirPath);
                AssetDatabase.Refresh();
            }

            settings = UnityEngine.ScriptableObject.CreateInstance<PopupGenerateSettings>();
            AssetDatabase.CreateAsset(settings, SettingsDefaultAssetPath);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            return settings;
        }

        static PopupGenerateSettings LoadSettings()
        {
            var guids = AssetDatabase.FindAssets($"t:{nameof(PopupGenerateSettings)}");
            if (guids.Length == 0)
            {
                return null;
            }

            if (guids.Length > 1)
            {
                Debug.LogWarning($"[PopupEntityFactoryGenerator] Multiple {nameof(PopupGenerateSettings)} found. Using the first one.");
            }

            var path = AssetDatabase.GUIDToAssetPath(guids[0]);
            return (PopupGenerateSettings)AssetDatabase.LoadAssetAtPath(path, typeof(PopupGenerateSettings));
        }
    }
}