// <auto-generated>
// This file is generated by ScreenStackEntityFactoryGenerator.
// DO NOT EDIT MANUALLY.
// </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using LighthouseExtends.ScreenStack;
using VContainer;
using SampleProduct.View.Scene.MainScene.Home.RequireToolsDialog;
using SampleProduct.View.Scene.MainScene.SampleTop.AnimationElement;
using SampleProduct.View.Scene.MainScene.SampleTop.ButtonElement;
using SampleProduct.View.Scene.MainScene.SampleTop.DialogElementDialog;
using SampleProduct.View.Scene.MainScene.SampleTop.DialogSample1Dialog;
using SampleProduct.View.Scene.MainScene.SampleTop.DialogSample2Dialog;
using SampleProduct.View.Scene.MainScene.SampleTop.DialogSampleConfirmDialog;
using SampleProduct.View.Scene.MainScene.SampleTop.InputLayerElement;
using SampleProduct.View.Scene.MainScene.SampleTop.OverlayElement;
using SampleProduct.View.Scene.MainScene.SampleTop.PopupElement;
using SampleProduct.View.Scene.MainScene.SampleTop.TextViewElement;
using SampleProduct.View.Scene.MainScene.SampleTop.TransitionAnimationElement;
using SampleProduct.View.Scene.MainScene.SceneSample1.SceneTransitionDialog;

namespace SampleProduct
{
    public sealed class ScreenStackEntityFactory : IScreenStackEntityFactory
    {
        readonly IObjectResolver objectResolver;
        readonly IScreenStackInstanceFactory screenStackInstanceFactory;

        public ScreenStackEntityFactory(IObjectResolver objectResolver, IScreenStackInstanceFactory screenStackInstanceFactory)
        {
            this.objectResolver = objectResolver;
            this.screenStackInstanceFactory = screenStackInstanceFactory;
        }

        public UniTask<ScreenStackEntity> CreateAsync(IScreenStackData data, CancellationToken ct)
        {
            return data switch
            {
                SceneTransitionData d => CreateScreenStackEntityAsync<SceneTransitionDialog, SceneTransitionData>("SceneTransitionDialog", d, ct),
                TransitionAnimationElementData d => CreateScreenStackEntityAsync<TransitionAnimationElementOverlay, TransitionAnimationElementData>("TransitionAnimationElementOverlay", d, ct),
                TextViewElementData d => CreateScreenStackEntityAsync<TextViewElementOverlay, TextViewElementData>("TextViewElementOverlay", d, ct),
                PopupElementData d => CreateScreenStackEntityAsync<PopupElementPopup, PopupElementData>("PopupElementPopup", d, ct),
                OverlayElementData d => CreateScreenStackEntityAsync<OverlayElementOverlay, OverlayElementData>("OverlayElementOverlay", d, ct),
                InputLayerElementData d => CreateScreenStackEntityAsync<InputLayerElementOverlay, InputLayerElementData>("InputLayerElementOverlay", d, ct),
                DialogSampleConfirmData d => CreateScreenStackEntityAsync<DialogSampleConfirmDialog, DialogSampleConfirmData>("DialogSampleConfirmDialog", d, ct),
                DialogSample2Data d => CreateScreenStackEntityAsync<DialogSample2Dialog, DialogSample2Data>("DialogSample2Dialog", d, ct),
                DialogSample1Data d => CreateScreenStackEntityAsync<DialogSample1Dialog, DialogSample1Data>("DialogSample1Dialog", d, ct),
                DialogElementData d => CreateScreenStackEntityAsync<DialogElementDialog, DialogElementData>("DialogElementDialog", d, ct),
                ButtonElementData d => CreateScreenStackEntityAsync<ButtonElementOverlay, ButtonElementData>("ButtonElementOverlay", d, ct),
                AnimationElementData d => CreateScreenStackEntityAsync<AnimationElementOverlay, AnimationElementData>("AnimationElementOverlay", d, ct),
                RequireToolsData d => CreateScreenStackEntityAsync<RequireToolsDialog, RequireToolsData>("RequireToolsDialog", d, ct),
                _ => throw new ArgumentOutOfRangeException(nameof(data), data.GetType().FullName, "Unknown screenStack data type")
            };
        }

        async UniTask<ScreenStackEntity> CreateScreenStackEntityAsync<TScreenStack, TScreenStackData>(
            string screenStackAddress,
            TScreenStackData data,
            CancellationToken ct)
            where TScreenStack : IScreenStack, IScreenStackSetup<TScreenStackData>
            where TScreenStackData : IScreenStackData
        {
            var screenStackInstance = await screenStackInstanceFactory.CreateScreenStackInstance<TScreenStack>(screenStackAddress, data, ct);
            objectResolver.Inject(screenStackInstance);
            screenStackInstance.Setup(data);
            return new ScreenStackEntity(screenStackInstance, data);
        }
    }
}
