// <auto-generated>
// This file is generated by ScreenStackEntityFactoryGenerator.
// DO NOT EDIT MANUALLY.
// </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using LighthouseExtends.ScreenStack;
using VContainer;
using SampleProduct.View.Scene.MainScene.Home.RequireToolsDialog;
using SampleProduct.View.Scene.MainScene.SampleTop.DialogSample1Dialog;
using SampleProduct.View.Scene.MainScene.SampleTop.DialogSample2Dialog;
using SampleProduct.View.Scene.MainScene.SampleTop.DialogSampleConfirmDialog;
using SampleProduct.View.Scene.MainScene.SceneSample1.SceneTransitionDialog;

namespace SampleProduct.LighthouseGenerated
{
    public sealed class ScreenStackEntityFactory : IScreenStackEntityFactory
    {
        readonly IObjectResolver objectResolver;
        readonly IScreenStackInstanceFactory screenStackInstanceFactory;

        public ScreenStackEntityFactory(IObjectResolver objectResolver, IScreenStackInstanceFactory screenStackInstanceFactory)
        {
            this.objectResolver = objectResolver;
            this.screenStackInstanceFactory = screenStackInstanceFactory;
        }

        public UniTask<ScreenStackEntity> CreateAsync(IScreenStackData data, CancellationToken ct)
        {
            return data switch
            {
                SceneTransitionData d => CreateScreenStackEntityAsync<SceneTransitionDialog, SceneTransitionPresenter, SceneTransitionData>("SceneTransitionDialog", d, ct),
                DialogSampleConfirmData d => CreateScreenStackEntityAsync<DialogSampleConfirmDialog, DialogSampleConfirmPresenter, DialogSampleConfirmData>("DialogSampleConfirmDialog", d, ct),
                DialogSample2Data d => CreateScreenStackEntityAsync<DialogSample2Dialog, DialogSample2Presenter, DialogSample2Data>("DialogSample2Dialog", d, ct),
                DialogSample1Data d => CreateScreenStackEntityAsync<DialogSample1Dialog, DialogSample1Presenter, DialogSample1Data>("DialogSample1Dialog", d, ct),
                RequireToolsData d => CreateScreenStackEntityAsync<RequireToolsDialog, RequireToolsPresenter, RequireToolsData>("RequireToolsDialog", d, ct),
                _ => throw new ArgumentOutOfRangeException(nameof(data), data.GetType().FullName, "Unknown screenStack data type")
            };
        }

        async UniTask<ScreenStackEntity> CreateScreenStackEntityAsync<TScreenStack, TScreenStackPresenter, TScreenStackData>(
            string screenStackAddress,
            TScreenStackData data,
            CancellationToken ct)
            where TScreenStack : IScreenStack, IScreenStackSetup<TScreenStackPresenter, TScreenStackData>
            where TScreenStackPresenter : IScreenStackPresenter, new()
            where TScreenStackData : IScreenStackData
        {
            var screenStackInstance = await screenStackInstanceFactory.CreateScreenStackInstance<TScreenStack>(screenStackAddress, ct);
            var screenStackPresenter = new TScreenStackPresenter();
            objectResolver.Inject(screenStackPresenter);
            screenStackInstance.Setup(screenStackPresenter, data);
            return new ScreenStackEntity(screenStackInstance, screenStackPresenter, data);
        }
    }
}
