using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using LighthouseExtends.InputLayer.Editor.ScriptableObject;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEngine;

namespace LighthouseExtends.InputLayer.Editor.ScriptGenerator
{
    public static class InputActionNamesGenerator
    {
        const string SettingsDefaultAssetPath = "Assets/Settings/InputLayerGenerateSettings.asset";

        [DidReloadScripts]
        static void OnScriptsReloaded()
        {
            Generate();
        }

        [MenuItem("Lighthouse/Generate/Auto/Generate \"InputActionNames\" manually")]
        static void GenerateFromMenu()
        {
            Generate();
        }

        [MenuItem("Lighthouse/Settings/InputLayerGenerateSettings")]
        static void ShowSettings()
        {
            var settings = LoadOrCreateSettings();
            if (settings != null)
            {
                Selection.activeObject = settings;
            }
        }

        static void Generate()
        {
            var settings = LoadSettings();
            if (settings == null || string.IsNullOrEmpty(settings.OutputFilePath))
            {
                return;
            }

            if (settings.InputActionAsset == null)
            {
                Debug.LogWarning("[InputActionNamesGenerator] InputActionAsset is not assigned in InputLayerGenerateSettings.");
                return;
            }

            var content = BuildContent(settings);
            WriteContent(content, settings.OutputFilePath);
        }

        static string BuildContent(InputLayerGenerateSettings settings)
        {
            var asset = settings.InputActionAsset;
            var sb = new StringBuilder();

            var mapNames = asset.actionMaps.Select(m => m.name).ToList();
            var actionNames = asset.actionMaps
                .SelectMany(m => m.actions)
                .Select(a => a.name)
                .Distinct()
                .OrderBy(n => n)
                .ToList();

            sb.AppendLine("// <auto-generated/>");

            if (!string.IsNullOrEmpty(settings.NamespaceName))
            {
                sb.AppendLine($"namespace {settings.NamespaceName}");
                sb.AppendLine("{");
                AppendClass(sb, settings.ClassName, mapNames, actionNames, "    ");
                sb.AppendLine("}");
            }
            else
            {
                AppendClass(sb, settings.ClassName, mapNames, actionNames, "");
            }

            return sb.ToString().Replace("\r\n", "\n");
        }

        static void AppendClass(StringBuilder sb, string className, List<string> mapNames, List<string> actionNames, string indent)
        {
            sb.AppendLine($"{indent}public static class {className}");
            sb.AppendLine($"{indent}{{");

            sb.AppendLine($"{indent}    public static class Maps");
            sb.AppendLine($"{indent}    {{");
            foreach (var mapName in mapNames)
            {
                sb.AppendLine($"{indent}        public const string {mapName} = \"{mapName}\";");
            }
            sb.AppendLine($"{indent}    }}");

            if (actionNames.Count > 0)
            {
                sb.AppendLine();
            }

            foreach (var actionName in actionNames)
            {
                sb.AppendLine($"{indent}    public const string {actionName} = \"{actionName}\";");
            }

            sb.AppendLine($"{indent}}}");
        }

        static void WriteContent(string content, string filePath)
        {
            var directoryPath = Path.GetDirectoryName(filePath);
            if (!Directory.Exists(directoryPath))
            {
                Directory.CreateDirectory(directoryPath);
            }

            if (File.Exists(filePath))
            {
                var existing = File.ReadAllText(filePath, Encoding.UTF8);
                if (existing == content)
                {
                    return;
                }
            }

            File.WriteAllText(filePath, content, new UTF8Encoding(false));

            var assetPath = "Assets" + filePath.Substring(Application.dataPath.Length).Replace('\\', '/');
            AssetDatabase.ImportAsset(assetPath, ImportAssetOptions.ForceUpdate);
            AssetDatabase.Refresh();
            Debug.Log("[InputActionNamesGenerator] Generated.");
        }

        static InputLayerGenerateSettings LoadOrCreateSettings()
        {
            var settings = LoadSettings();
            if (settings != null)
            {
                return settings;
            }

            var fsDirPath = Path.Combine(Application.dataPath, "Settings");
            if (!Directory.Exists(fsDirPath))
            {
                Directory.CreateDirectory(fsDirPath);
                AssetDatabase.Refresh();
            }

            settings = UnityEngine.ScriptableObject.CreateInstance<InputLayerGenerateSettings>();
            AssetDatabase.CreateAsset(settings, SettingsDefaultAssetPath);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            return settings;
        }

        static InputLayerGenerateSettings LoadSettings()
        {
            var guids = AssetDatabase.FindAssets($"t:{nameof(InputLayerGenerateSettings)}");
            if (guids.Length == 0)
            {
                return null;
            }

            if (guids.Length > 1)
            {
                Debug.LogWarning($"[InputActionNamesGenerator] Multiple {nameof(InputLayerGenerateSettings)} found. Using the first one.");
            }

            var path = AssetDatabase.GUIDToAssetPath(guids[0]);
            return (InputLayerGenerateSettings)AssetDatabase.LoadAssetAtPath(path, typeof(InputLayerGenerateSettings));
        }
    }
}
