using System.IO;
using System.Linq;
using System.Text;
using Lighthouse.Core.ScriptableObject;
using UnityEditor;
using UnityEngine;

namespace Lighthouse.Core.ScriptGenerator
{
    [InitializeOnLoad]
    public static class SceneIdGenerator
    {
        static SceneIdGenerator()
        {
            EditorBuildSettings.sceneListChanged += OnSceneListChanged;
        }

        static void OnSceneListChanged()
        {
            GenerateMainSceneId();
            GenerateCommonSceneId();
        }

        [MenuItem("Lighthouse/Auto Generate/Generate Main SceneId")]
        static void GenerateMainSceneId()
        {
            var generateSettings = LighthouseEditor.GetSettings<GenerateSettings>();
            GenerateSceneId("Main", generateSettings.MainSceneIdFilePath, generateSettings.ProductNameSpace);
        }

        [MenuItem("Lighthouse/Auto Generate/Generate Common SceneId")]
        static void GenerateCommonSceneId()
        {
            var generateSettings = LighthouseEditor.GetSettings<GenerateSettings>();
            GenerateSceneId("Common", generateSettings.CommonSceneIdFilePath, generateSettings.ProductNameSpace);
        }

        static void GenerateSceneId(string sceneIdType, string outputPath, string nameSpace)
        {
            var scenes = EditorBuildSettings.scenes
                .Where(s => s.enabled)
                .Select(s => s.path)
                .Where(p => !string.IsNullOrWhiteSpace(p) && p.Contains($"{sceneIdType}Scene"))
                .Distinct()
                .ToArray();

            var content = BuildContent(sceneIdType, scenes, nameSpace);
            var result = WriteContent(content, outputPath);
            if (!result)
            {
                Debug.LogError("[SceneIdGenerator] Failed to generate SceneID");
                return;
            }

            AssetDatabase.ImportAsset(outputPath, ImportAssetOptions.ForceUpdate);
            AssetDatabase.Refresh();
            Debug.Log("[SceneIdGenerator] Generated.");
        }

        static string BuildContent(string sceneIdType, string[] sceneNames, string nameSpace)
        {
            if (sceneNames.Length == 0)
            {
                Debug.LogError("[SceneIdGenerator] No enabled scenes found in Build Settings.");
            }

            var sb = new StringBuilder(8 * 1024);

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated by SceneIdGenerator.");
            sb.AppendLine("// DO NOT EDIT MANUALLY.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using Lighthouse.Core;");
            sb.AppendLine("using Lighthouse.Core.Scene;");
            sb.AppendLine();
            sb.AppendLine($"namespace {nameSpace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public sealed class {sceneIdType}SceneId : {sceneIdType}SceneKey");
            sb.AppendLine("    {");

            byte id = 1;

            // None
            sb.AppendLine($"        public static readonly {sceneIdType}SceneId None = new {sceneIdType}SceneId({id}, string.Empty);");

            id++;

            foreach (var sceneName in sceneNames)
            {
                var validSceneName = Path.GetFileNameWithoutExtension(sceneName);
                var identifier = SanitizeIdentifier(validSceneName);

                sb.AppendLine($"        public static readonly {sceneIdType}SceneId {identifier} = new {sceneIdType}SceneId({id}, \"{validSceneName}\");");

                id++;
            }

            sb.AppendLine();
            sb.AppendLine($"        public static ReadOnlySpan<{sceneIdType}SceneId> All");
            sb.AppendLine("        {");
            sb.AppendLine("            get");
            sb.AppendLine("            {");
            sb.AppendLine($"                return new {sceneIdType}SceneId[]");
            sb.AppendLine("                {");
            sb.AppendLine("                    None,");

            foreach (var sceneName in sceneNames)
            {
                var validSceneName = Path.GetFileNameWithoutExtension(sceneName);
                var identifier = SanitizeIdentifier(validSceneName);

                sb.AppendLine($"                    {identifier},");
            }

            sb.AppendLine("                };");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        {sceneIdType}SceneId(byte id, string name) : base(id, name)");
            sb.AppendLine("        {");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        static bool WriteContent(string content, string sceneIdFilePath)
        {
            var directoryPath = Path.GetDirectoryName(sceneIdFilePath);
            if (!Directory.Exists(directoryPath))
            {
                Directory.CreateDirectory(directoryPath);
            }

            if (File.Exists(sceneIdFilePath))
            {
                var existing = File.ReadAllText(sceneIdFilePath, Encoding.UTF8);
                if (existing == content)
                {
                    return true;
                }
            }

            File.WriteAllText(sceneIdFilePath, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            return true;
        }

        static string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                return "_Scene";
            }

            var sb = new StringBuilder(name.Length);

            for (var i = 0; i < name.Length; i++)
            {
                var c = name[i];

                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sb.Append(c);
                }
                else
                {
                    sb.Append('_');
                }
            }

            if (char.IsDigit(sb[0]))
            {
                sb.Insert(0, '_');
            }

            return sb.ToString();
        }
    }
}