using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using LighthouseExtends.ScreenStack.Editor.ScriptableObject;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEngine;

namespace LighthouseExtends.ScreenStack.Editor.ScriptGenerator
{
    public static class ScreenStackEntityFactoryGenerator
    {
        const string SettingsDefaultAssetPath = "Assets/Settings/ScreenStackGenerateSettings.asset";

        [DidReloadScripts]
        static void OnScriptsReloaded()
        {
            Generate();
        }

        [MenuItem("Lighthouse/Auto Generate/Generate ScreenStack Entity Factory")]
        static void GenerateFromMenu()
        {
            Generate();
        }

        [MenuItem("Lighthouse/Settings/ScreenStackGenerateSettings")]
        static void ShowSettings()
        {
            var settings = LoadOrCreateSettings();
            if (settings != null)
            {
                Selection.activeObject = settings;
            }
        }

        static void Generate()
        {
            var settings = LoadSettings();
            if (settings == null || string.IsNullOrEmpty(settings.ScreenStackEntityFactoryFilePath))
            {
                return;
            }

            var screenStackDataInterface = typeof(IScreenStackData);
            var screenStackSetupOpenType = typeof(IScreenStackSetup<,>);

            var allTypes = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(SafeGetTypes)
                .ToArray();

            var dataTypes = allTypes
                .Where(t => t.IsClass && !t.IsAbstract && screenStackDataInterface.IsAssignableFrom(t))
                .ToArray();

            if (dataTypes.Length == 0)
            {
                return;
            }

            var mappings = new List<(Type Data, Type ScreenStack, Type Presenter)>();

            foreach (var dataType in dataTypes)
            {
                var screenStackType = allTypes.FirstOrDefault(t =>
                    t.IsClass && !t.IsAbstract &&
                    t.GetInterfaces().Any(i =>
                        i.IsGenericType &&
                        i.GetGenericTypeDefinition() == screenStackSetupOpenType &&
                        i.GetGenericArguments()[1] == dataType));

                if (screenStackType == null)
                {
                    Debug.LogWarning($"[ScreenStackEntityFactoryGenerator] No IScreenStackSetup implementation found for {dataType.Name}. Skipped.");
                    continue;
                }

                var setupInterface = screenStackType.GetInterfaces().First(i =>
                    i.IsGenericType &&
                    i.GetGenericTypeDefinition() == screenStackSetupOpenType &&
                    i.GetGenericArguments()[1] == dataType);

                var presenterType = setupInterface.GetGenericArguments()[0];
                mappings.Add((dataType, screenStackType, presenterType));
            }

            if (mappings.Count == 0)
            {
                return;
            }

            var content = BuildContent(settings.ScreenStackEntityFactoryClassName, settings.ScreenStackEntityFactoryNamespace, mappings);
            WriteContent(content, settings.ScreenStackEntityFactoryFilePath);
        }

        static string BuildContent(string className, string namespaceName, List<(Type Data, Type ScreenStack, Type Presenter)> mappings)
        {
            var extraNamespaces = mappings
                .SelectMany(m => new[] { m.Data.Namespace, m.ScreenStack.Namespace, m.Presenter.Namespace })
                .Where(ns => !string.IsNullOrEmpty(ns) && ns != namespaceName)
                .Distinct()
                .OrderBy(ns => ns)
                .ToArray();

            var sb = new StringBuilder(4 * 1024);

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated by ScreenStackEntityFactoryGenerator.");
            sb.AppendLine("// DO NOT EDIT MANUALLY.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine("using LighthouseExtends.ScreenStack;");
            sb.AppendLine("using VContainer;");
            foreach (var ns in extraNamespaces)
            {
                sb.AppendLine($"using {ns};");
            }
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public sealed class {className} : IScreenStackEntityFactory");
            sb.AppendLine("    {");
            sb.AppendLine("        readonly IObjectResolver objectResolver;");
            sb.AppendLine("        readonly IScreenStackInstanceFactory screenStackInstanceFactory;");
            sb.AppendLine();
            sb.AppendLine($"        public {className}(IObjectResolver objectResolver, IScreenStackInstanceFactory screenStackInstanceFactory)");
            sb.AppendLine("        {");
            sb.AppendLine("            this.objectResolver = objectResolver;");
            sb.AppendLine("            this.screenStackInstanceFactory = screenStackInstanceFactory;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public UniTask<ScreenStackEntity> CreateAsync(IScreenStackData data, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine("            return data switch");
            sb.AppendLine("            {");
            foreach (var (dataType, screenStackType, presenterType) in mappings)
            {
                sb.AppendLine($"                {dataType.Name} d => CreateScreenStackEntityAsync<{screenStackType.Name}, {presenterType.Name}, {dataType.Name}>(\"{screenStackType.Name}\", d, ct),");
            }
            sb.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(data), data.GetType().FullName, \"Unknown screenStack data type\")");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        async UniTask<ScreenStackEntity> CreateScreenStackEntityAsync<TScreenStack, TScreenStackPresenter, TScreenStackData>(");
            sb.AppendLine("            string screenStackAddress,");
            sb.AppendLine("            TScreenStackData data,");
            sb.AppendLine("            CancellationToken ct)");
            sb.AppendLine("            where TScreenStack : IScreenStack, IScreenStackSetup<TScreenStackPresenter, TScreenStackData>");
            sb.AppendLine("            where TScreenStackPresenter : IScreenStackPresenter, new()");
            sb.AppendLine("            where TScreenStackData : IScreenStackData");
            sb.AppendLine("        {");
            sb.AppendLine("            var screenStackInstance = await screenStackInstanceFactory.CreateScreenStackInstance<TScreenStack>(screenStackAddress, ct);");
            sb.AppendLine("            var screenStackPresenter = new TScreenStackPresenter();");
            sb.AppendLine("            objectResolver.Inject(screenStackPresenter);");
            sb.AppendLine("            screenStackInstance.Setup(screenStackPresenter, data);");
            sb.AppendLine("            return new ScreenStackEntity(screenStackInstance, screenStackPresenter, data);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        static void WriteContent(string content, string filePath)
        {
            var directoryPath = Path.GetDirectoryName(filePath);
            if (!Directory.Exists(directoryPath))
            {
                Directory.CreateDirectory(directoryPath);
            }

            if (File.Exists(filePath))
            {
                var existing = File.ReadAllText(filePath, Encoding.UTF8);
                if (existing == content)
                {
                    return;
                }
            }

            File.WriteAllText(filePath, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

            var assetPath = "Assets" + filePath.Substring(Application.dataPath.Length).Replace('\\', '/');
            AssetDatabase.ImportAsset(assetPath, ImportAssetOptions.ForceUpdate);
            AssetDatabase.Refresh();
            Debug.Log("[ScreenStackEntityFactoryGenerator] Generated.");
        }

        static IEnumerable<Type> SafeGetTypes(System.Reflection.Assembly assembly)
        {
            try
            {
                return assembly.GetTypes();
            }
            catch
            {
                return Array.Empty<Type>();
            }
        }

        static ScreenStackGenerateSettings LoadOrCreateSettings()
        {
            var settings = LoadSettings();
            if (settings != null)
            {
                return settings;
            }

            var fsDirPath = Path.Combine(Application.dataPath, "Settings");
            if (!Directory.Exists(fsDirPath))
            {
                Directory.CreateDirectory(fsDirPath);
                AssetDatabase.Refresh();
            }

            settings = UnityEngine.ScriptableObject.CreateInstance<ScreenStackGenerateSettings>();
            AssetDatabase.CreateAsset(settings, SettingsDefaultAssetPath);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            return settings;
        }

        static ScreenStackGenerateSettings LoadSettings()
        {
            var guids = AssetDatabase.FindAssets($"t:{nameof(ScreenStackGenerateSettings)}");
            if (guids.Length == 0)
            {
                return null;
            }

            if (guids.Length > 1)
            {
                Debug.LogWarning($"[ScreenStackEntityFactoryGenerator] Multiple {nameof(ScreenStackGenerateSettings)} found. Using the first one.");
            }

            var path = AssetDatabase.GUIDToAssetPath(guids[0]);
            return (ScreenStackGenerateSettings)AssetDatabase.LoadAssetAtPath(path, typeof(ScreenStackGenerateSettings));
        }
    }
}