// <auto-generated>
// This file is generated by PopupEntityFactoryGenerator.
// DO NOT EDIT MANUALLY.
// </auto-generated>

using System;
using System.Threading;
using Cysharp.Threading.Tasks;
using LighthouseExtends.Popup;
using VContainer;
using SampleProduct.View.Common.Popup;

namespace SampleProduct
{
    public sealed class PopupEntityFactory : IPopupEntityFactory
    {
        readonly IObjectResolver objectResolver;
        readonly IPopupInstanceFactory popupInstanceFactory;

        public PopupEntityFactory(IObjectResolver objectResolver, IPopupInstanceFactory popupInstanceFactory)
        {
            this.objectResolver = objectResolver;
            this.popupInstanceFactory = popupInstanceFactory;
        }

        public UniTask<PopupEntity> CreateAsync(IPopupData data, CancellationToken ct)
        {
            return data switch
            {
                PopupSample1PopupData d => CreatePopupEntityAsync<PopupSample1Popup, PopupSample1PopupPresenter, PopupSample1PopupData>("PopupSample1Popup", d, ct),
                PopupSample2PopupData d => CreatePopupEntityAsync<PopupSample2Popup, PopupSample2PopupPresenter, PopupSample2PopupData>("PopupSample2Popup", d, ct),
                PopupSampleConfirmPopupData d => CreatePopupEntityAsync<PopupSampleConfirmPopup, PopupSampleConfirmPopupPresenter, PopupSampleConfirmPopupData>("PopupSampleConfirmPopup", d, ct),
                _ => throw new ArgumentOutOfRangeException(nameof(data), data.GetType().FullName, "Unknown popup data type")
            };
        }

        async UniTask<PopupEntity> CreatePopupEntityAsync<TPopup, TPopupPresenter, TPopupData>(
            string popupAddress,
            TPopupData data,
            CancellationToken ct)
            where TPopup : IPopup, IPopupSetup<TPopupPresenter, TPopupData>
            where TPopupPresenter : IPopupPresenter, new()
            where TPopupData : IPopupData
        {
            var popupInstance = await popupInstanceFactory.CreatePopupInstance<TPopup>(popupAddress, ct);
            var popupPresenter = new TPopupPresenter();
            objectResolver.Inject(popupPresenter);
            popupInstance.Setup(popupPresenter, data);
            return new PopupEntity(popupInstance, popupPresenter, data);
        }
    }
}
