// <auto-generated>
// This file is generated by SceneIdGenerator.
// DO NOT EDIT MANUALLY.
// </auto-generated>

using System;
using Lighthouse.Core;
using Lighthouse.Core.Scene;

namespace ProductNameSpace
{
    public static class SampleProductSceneModuleId
    {
        public static readonly SceneModuleId None = new SceneModuleId(1, string.Empty);
        public static readonly SceneModuleId GlobalHeader = new SceneModuleId(2, "GlobalHeader");
        public static readonly SceneModuleId Overlay = new SceneModuleId(3, "Overlay");
        public static readonly SceneModuleId Background = new SceneModuleId(4, "Background");

        public static ReadOnlySpan<SceneModuleId> All
        {
            get
            {
                return new SceneModuleId[]
                {
                    None,
                    GlobalHeader,
                    Overlay,
                    Background,
                };
            }
        }
    }
}
