// <auto-generated>
// This file is generated by SceneIdGenerator.
// DO NOT EDIT MANUALLY.
// </auto-generated>

using System;
using Lighthouse.Scene;

namespace SampleProduct
{
    public static class SampleProductMainSceneId
    {
        public static readonly MainSceneId None = new MainSceneId(1, string.Empty);
        public static readonly MainSceneId Splash = new MainSceneId(2, "Splash");
        public static readonly MainSceneId Title = new MainSceneId(3, "Title");
        public static readonly MainSceneId Home = new MainSceneId(4, "Home");
        public static readonly MainSceneId Edit = new MainSceneId(5, "Edit");
        public static readonly MainSceneId SceneSample1 = new MainSceneId(6, "SceneSample1");
        public static readonly MainSceneId SceneSample2 = new MainSceneId(7, "SceneSample2");

        public static ReadOnlySpan<MainSceneId> All
        {
            get
            {
                return new MainSceneId[]
                {
                    None,
                    Splash,
                    Title,
                    Home,
                    Edit,
                    SceneSample1,
                    SceneSample2,
                };
            }
        }
    }
}
