// <auto-generated>
// This file is generated by SceneIdGenerator.
// DO NOT EDIT MANUALLY.
// </auto-generated>

using System;
using Lighthouse.Core;
using Lighthouse.Core.Scene;

namespace SampleProduct
{
    public static class SampleProductModuleSceneId
    {
        public static readonly ModuleSceneId None = new ModuleSceneId(1, string.Empty);
        public static readonly ModuleSceneId GlobalHeader = new ModuleSceneId(2, "GlobalHeader");
        public static readonly ModuleSceneId Overlay = new ModuleSceneId(3, "Overlay");
        public static readonly ModuleSceneId Background = new ModuleSceneId(4, "Background");

        public static ReadOnlySpan<ModuleSceneId> All
        {
            get
            {
                return new ModuleSceneId[]
                {
                    None,
                    GlobalHeader,
                    Overlay,
                    Background,
                };
            }
        }
    }
}
